name: Build and Release Java Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install gdown (Google Drive Downloader)
        run: pip install gdown

      - name: Download large build files from Google Drive
        run: |
          mkdir -p ~/wz  # Ensure the directory exists
          gdown --id 1EJfQtXv8xofabqSPpJs7oOgtanAVtEKv -O wz.tar
          tar -xvf wz.tar -C ~/wz

      - name: Run tests with debug logging
        run: mvn test -X || true  # Run tests, but prevent failure from stopping workflow
      
      - name: Build with Maven (Ignore Test Failures)
        run: mvn clean package -Dmaven.test.failure.ignore=true

      - name: Upload JAR artifact (Always for CI)
        uses: actions/upload-artifact@v4
        with:
          name: mapleglory-jar
          path: target/mapleglory.jar

      - name: Release to GitHub (Only if commit message starts with 'release:')
        if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'release:')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "Automated release of the project."
          draft: false
          prerelease: false
          files: target/mapleglory.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Using PAT instead of default GITHUB_TOKEN